# Generated by Django 2.0.4 on 2018-05-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_month_last_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
